import time

questions = ['> 1) What was the Axis Powers?',
             '> 2) What was the Allied Powers?',
             '> 3) What was the War Guilt clause?',
             '> 4) What is Facism?',
             '> 5) What is the Nazi Party?',
             '> 6) What is Totalitarianism?',
             '> 7) What is Appeasement?',
             '> 8) What is Nationalism?',
             '> 9) What is Communism?',
             '> 10) Who were Bolsheviks?',
             '> 11) Who was Vladimir Lenin?',
             '> 12) What is Refute?',
             '> 13) What is Opposition?',
             '> 14) What is Socialism?',
             '> 15) What is Vengence?',
             '> 16) Who was Adolf Hitler?',
             '> 17) Who was Woodrow Wilson?',
             '> 18) What was the League of Nations?',
             '> 19) What is Isolationism?',
             '> 20) What is the Treaty Of Versailles?',
             '> 21) Who was Joseph Stalin?',
             '> 22) Who was Winston Churchill?',
             '> 23) What is Disarmament?',
             '> 24) What were the 14 Points (Created by Woodrow Wilson for the \'peace without victory\')',
             '> 25) What is Reparations?',
             '> 26) What is the Treaty of Brest-Litovsk?']
answers = ['']
